server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: h2
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
            
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
            
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
            
        - id: loyalty-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/loyalty/**
          filters:
            - StripPrefix=2
            
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2
            
        - id: analytics-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2
            
        - id: store-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/stores/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
