services:
  # Database
  postgres-users:
    image: postgres:15
    container_name: postgres-users
    environment:
      POSTGRES_DB: coffeeshop_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-products:
    image: postgres:15
    container_name: postgres-products
    environment:
      POSTGRES_DB: coffeeshop_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-orders:
    image: postgres:15
    container_name: postgres-orders
    environment:
      POSTGRES_DB: coffeeshop_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-payments:
    image: postgres:15
    container_name: postgres-payments
    environment:
      POSTGRES_DB: coffeeshop_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-loyalty:
    image: postgres:15
    container_name: postgres-loyalty
    environment:
      POSTGRES_DB: coffeeshop_loyalty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_loyalty_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-notifications:
    image: postgres:15
    container_name: postgres-notifications
    environment:
      POSTGRES_DB: coffeeshop_notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    volumes:
      - postgres_notifications_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-analytics:
    image: postgres:15
    container_name: postgres-analytics
    environment:
      POSTGRES_DB: coffeeshop_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  postgres-stores:
    image: postgres:15
    container_name: postgres-stores
    environment:
      POSTGRES_DB: coffeeshop_stores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - postgres_stores_data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - coffee-shop-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - coffee-shop-network

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - coffee-shop-network

  # Eureka Server
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
    networks:
      - coffee-shop-network

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres-users
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # Product Service
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-products
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # Order Service
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres-orders
      - redis
      - rabbitmq
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBITMQ_HOST: rabbitmq
      ZIPKIN_BASE_URL: http://zipkin:9411
    networks:
      - coffee-shop-network

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres-payments
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # Loyalty Service
  loyalty-service:
    build:
      context: .
      dockerfile: loyalty-service/Dockerfile
    container_name: loyalty-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - postgres-loyalty
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - postgres-notifications
      - redis
      - rabbitmq
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBITMQ_HOST: rabbitmq
      ZIPKIN_BASE_URL: http://zipkin:9411
    networks:
      - coffee-shop-network

  # Analytics Service
  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: analytics-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - postgres-analytics
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

  # Store Service
  store-service:
    build:
      context: .
      dockerfile: store-service/Dockerfile
    container_name: store-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - postgres-stores
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coffee-shop-network

volumes:
  postgres_users_data:
  postgres_products_data:
  postgres_orders_data:
  postgres_payments_data:
  postgres_loyalty_data:
  postgres_notifications_data:
  postgres_analytics_data:
  postgres_stores_data:
  rabbitmq_data:


networks:
  coffee-shop-network:
    driver: bridge
