server:
  port: 8083

spring:
  application:
    name: order-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/coffeeshop_orders
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    exchange: order.exchange
    routing-key:
      order-created: order.created

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
